### ISSUE TITLE
argocd access

### ISSUE THREAD

**Issue by goern** [operate-first/argocd-apps#18]
As an Application Owner/Project-specific DevOps,
I want to get access to ArgoCD Web UI
so that I can see the status of my deployments

**Comment by HumairAK** [comment]
I'll update the readme with a link to the ArgoCD console. I already had you and @harshad16 added to the `thoth` openshift group on moc (see [here](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/53) for the pr), so you guys can login and see apps belonging to the `thoth` argocd project in the console [here](https://argocd-server-argocd.apps.cnv.massopen.cloud)
