### ISSUE TITLE
Resource argoproj.io:WorkflowTemplate is not permitted in project thoth.

### ISSUE THREAD

**Issue by harshad16** [operate-first/argocd-apps#22]
The application is erroring out as the resource WorkflowTemplate is not allowed. 
May be it has to be included in https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/blob/master/manifests/argocd/overlays/prod/projects/thoth.yaml
![workflowtemplate](https://user-images.githubusercontent.com/14028058/101539285-50637280-39c4-11eb-8318-234f96d1c272.png)

**Comment by tumido** [comment]
It seems to be included there though. @HumairAK do you know what's up? 

https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/blob/master/manifests/argocd/overlays/prod/projects/thoth.yaml#L69-70

**Comment by harshad16** [comment]
This was fix with the MR https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/merge_requests/19
thanks @HumairAK  and @4n4nd.
