### ISSUE TITLE
Resource argoproj.io:WorkflowTemplate is not permitted in project thoth.

### ISSUE THREAD

**Issue by goern** [operate-first/argocd-apps#27]
See for example: https://argocd-server-argocd.apps.cnv.massopen.cloud/applications/prod-thoth-solver?operation=false

**Comment by goern** [comment]
Cc: @harshad16

**Comment by goern** [comment]
Cc: @HumairAK

**Comment by tumido** [comment]
I think it was just stale logs. The `WorkflowTemplates` were already synced with the rest of the resources:
![image](https://user-images.githubusercontent.com/7453394/102604313-49570580-4124-11eb-8e79-a66ff53bd165.png)

And the resource kind itself is permitted for Thoth:
https://github.com/open-infrastructure-labs/moc-cnv-sandbox/blob/494f33cd8e348b3bab4a3cd01bf099614c5d9641/manifests/argocd/overlays/prod/projects/thoth.yaml#L70-L71

I've just rerun the sync manually selectively on the 2 `WorkflowTemplates` resources and it cleared the log:
![image](https://user-images.githubusercontent.com/7453394/102604415-6d1a4b80-4124-11eb-84a1-422f9fafeb2c.png)
