### ISSUE TITLE
Grafanadatasources are not synced by argocd

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/argocd-apps#33]
The example Grafanadatasource in [operate-first/apps](https://github.com/operate-first/apps/blob/master/observatorium/overlays/moc/kustomization.yaml#L9) was not synced by ArgoCD

**Comment by HumairAK** [comment]
Can you add [this](https://github.com/operate-first/argocd-apps/blob/main/overlays/moc/operate-first/observatorium.yaml) to [this](https://github.com/operate-first/argocd-apps/blob/main/overlays/moc/operate-first/kustomization.yaml) ?
