### ISSUE TITLE
migrate Thoth's Prow from GKE to Op1st workload cluster

### ISSUE THREAD

**Issue by goern** [operate-first/argocd-apps#34]
ssia

/kind feature
/label sig/devops
/priority important-soon
/assign @harshad16 
/assign @goern

**Comment by goern** [comment]
https://github.com/operate-first/argocd-apps/pull/37

**Comment by harshad16** [comment]
Prow is setup to be running in operate-first 
and has been serving AICoE and operate-first users. 
closing the issue.
