### ISSUE TITLE
Prow not being deployed by ArgoCD

### ISSUE THREAD

**Issue by goern** [operate-first/argocd-apps#42]
after Harshad fixed my proken #37  by merging #41 the app is not being deployed. and I cant see it at https://argocd-server-argocd.apps.cnv.massopen.cloud/applications 

any hints?

/kind bug
/label sig/devops
Related-To: #34

**Comment by tumido** [comment]
I think you'd need to log out and back it to ArgoCD so your user's new group membership gets propagated to ArgoCD. I can see the app in there and it's all green. :wink:

**Comment by HumairAK** [comment]
Looks like this is resolved, and the app is deploying. Please re-open if needed.
