### ISSUE TITLE
Make AppProjects deployed to all dowstreams

### ISSUE THREAD

**Issue by tumido** [operate-first/argocd-apps#43]
Context: Currently the ArgoCD setup does fully work in MOC settings only. The `Applications` are deployable to all the downstreams, yet they are required to be deployed to projects which don't exist in these downstream deployments.

https://github.com/operate-first/argocd-apps/pull/36#discussion_r561182034

Outcome:
Ensure that any app can be successfully deployed to other downstreams without any ops related blocker

**Comment by HumairAK** [comment]
hrmm not sure if this is still relevant, but it seems stale. All aplications/projects are deployed on infra, so I don't think this is relevant any more -- correct me if I'm wrong. If we still need to do this please re-open in the apps repo.
